"use client";

// ============================================================
// features/simulation/AIInsightsCard.tsx
// Displays the AI-generated executive summary, benefits, risks, recommendations
// ============================================================

import { motion } from "framer-motion";
import { AIInsights } from "@/types";
import { CheckCircle, AlertCircle, Lightbulb, FileText } from "lucide-react";

interface AIInsightsCardProps {
  insights: AIInsights;
  onExportReport: () => void;
}

export function AIInsightsCard({ insights, onExportReport }: AIInsightsCardProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: 0.2 }}
      className="rounded-xl overflow-hidden"
      style={{ border: "1px solid hsl(var(--border))" }}
    >
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-4"
        style={{
          background: "linear-gradient(135deg, hsl(222 47% 11%), hsl(217 33% 17%))",
          borderBottom: "1px solid hsl(var(--sidebar-border))",
        }}>
        <div className="flex items-center gap-2">
          <span className="text-lg">✨</span>
          <div>
            <p className="text-white font-semibold text-sm">AI Planning Insights</p>
            <p className="text-xs" style={{ color: "hsl(215 20% 55%)" }}>Generated by Google Gemini</p>
          </div>
        </div>
        <button
          onClick={onExportReport}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-white transition-all"
          style={{
            background: "hsl(217 91% 60% / 0.3)",
            border: "1px solid hsl(217 91% 60% / 0.4)",
          }}
        >
          <FileText className="w-3.5 h-3.5" />
          Export PDF
        </button>
      </div>

      <div className="p-5 space-y-5" style={{ background: "hsl(var(--card))" }}>
        {/* Executive Summary */}
        <div>
          <p className="text-xs font-semibold mb-2" style={{ color: "hsl(var(--muted-foreground))" }}>
            EXECUTIVE SUMMARY
          </p>
          <p className="text-sm leading-relaxed">{insights.executive_summary}</p>
        </div>

        {/* Benefits + Risks side by side */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {/* Benefits */}
          <div className="rounded-xl p-4 space-y-2"
            style={{ background: "hsl(142 71% 45% / 0.06)", border: "1px solid hsl(142 71% 45% / 0.2)" }}>
            <div className="flex items-center gap-1.5 mb-3">
              <CheckCircle className="w-4 h-4" style={{ color: "hsl(142 71% 45%)" }} />
              <p className="text-xs font-semibold" style={{ color: "hsl(142 71% 45%)" }}>Benefits</p>
            </div>
            {insights.benefits.map((benefit, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1 * i }}
                className="flex items-start gap-2"
              >
                <span className="text-xs mt-0.5" style={{ color: "hsl(142 71% 45%)" }}>✓</span>
                <p className="text-xs leading-relaxed">{benefit}</p>
              </motion.div>
            ))}
          </div>

          {/* Risks */}
          <div className="rounded-xl p-4 space-y-2"
            style={{ background: "hsl(0 84% 60% / 0.06)", border: "1px solid hsl(0 84% 60% / 0.2)" }}>
            <div className="flex items-center gap-1.5 mb-3">
              <AlertCircle className="w-4 h-4" style={{ color: "hsl(0 84% 60%)" }} />
              <p className="text-xs font-semibold" style={{ color: "hsl(0 84% 60%)" }}>Risks & Concerns</p>
            </div>
            {insights.risks.map((risk, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1 * i }}
                className="flex items-start gap-2"
              >
                <span className="text-xs mt-0.5" style={{ color: "hsl(0 84% 60%)" }}>⚠</span>
                <p className="text-xs leading-relaxed">{risk}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Recommendations */}
        <div className="rounded-xl p-4"
          style={{ background: "hsl(217 91% 60% / 0.06)", border: "1px solid hsl(217 91% 60% / 0.2)" }}>
          <div className="flex items-center gap-1.5 mb-3">
            <Lightbulb className="w-4 h-4" style={{ color: "hsl(217 91% 60%)" }} />
            <p className="text-xs font-semibold" style={{ color: "hsl(217 91% 60%)" }}>Recommendations</p>
          </div>
          <div className="space-y-2">
            {insights.recommendations.map((rec, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 * i }}
                className="flex items-start gap-2"
              >
                <span className="font-bold text-xs flex-shrink-0 w-5 h-5 rounded-full flex items-center justify-center"
                  style={{ background: "hsl(217 91% 60% / 0.2)", color: "hsl(217 91% 60%)" }}>
                  {i + 1}
                </span>
                <p className="text-xs leading-relaxed">{rec}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  );
}
